Medicus/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medicus.Models
{
    public class Order : BaseEntity
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Required]
        public string CustomerId { get; set; }

        //[Required]
        //public int AddressId { get; set; }

        //[Required]
        //public int CreditCardId { get; set; }

        [Display(Name = "Fulfilled Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime? FullFilledDate { get; set; }

        [Required]
        public OrderStatus Status { get; set; }

        [Display(Name = "Total Price")]
        [DisplayFormat(DataFormatString = "€ {0:N2}")]
        public decimal TotalPrice { get; set; }

        [Display(Name = "Credit Card")]
        public virtual CreditCard CreditCard { get; set; }

        [Display(Name = "Shipping Address")]
        public virtual ShippingAddress Address { get; set; }

        [Display(Name = "Order Items")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }

        public virtual ApplicationUser Customer { get; set; }

        public void UpdateOrders()
        {
            ICollection<Order> orders = db.Orders.ToList();
            DateTime now = DateTime.UtcNow;
            foreach (Order order in orders)
            {
                long timePassed = (long)(now - order.CreatedOn).TotalMinutes;
                if (timePassed >= 15 && timePassed < 2 * 60)            order.Status = OrderStatus.Submitted;   //Set Submitted after 15'
                if (timePassed >= 2 * 60  && timePassed < 48 * 60)      order.Status = OrderStatus.Shipped;     //Set Shipped after 2 hours
                if (timePassed >= 48 * 60 && timePassed < 24 * 7 * 60)  order.Status = OrderStatus.Delivered;   //Set Delivered after 2 days
                if (timePassed >= 24 * 7 * 60)                          order.Status = OrderStatus.Completed;   //Set Completed after 7 days
                if (order.Status == OrderStatus.Completed) order.FullFilledDate = order.CreatedOn + new TimeSpan(7, 0, 0, 0); //Set Fullfilled date after 7 days
            }
            db.SaveChanges();
        }
    }

    public enum OrderStatus
    {
        [Display(Name = "Received")]
        Received,
        [Display(Name = "Submitted")]
        Submitted,
        [Display(Name = "Shipped")]
        Shipped,
        [Display(Name = "Delivered")]
        Delivered,
        [Display(Name = "Completed")]
        Completed
    }

}

Medicus/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Medicus.Models
{
    public class OrderViewModel
    {
        private Order order;

        public OrderViewModel(Order order)
        {
            this.order = order;
        }

        public int Id { get { return order.Id; } }

        [Display(Name = "Fulfilled Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime? FullfilledDate { get { return order.FullFilledDate;  } }

        [Display(Name = "Customer")]
        //public string CustomerName { get { return order.Customer.UserName; } } //prevent circular reference that Json doesn't like
        public string CustomerName { get; set; } 

        [Display(Name = "Total Price")]
        //[DisplayFormat(DataFormatString = "{0:N2}")]
        public string TotalPrice { get { return String.Format("€ {0:N2}", order.TotalPrice); } }

        [Display(Name = "Status")]
        public OrderStatus Status { get { return order.Status; } }

        [Display(Name = "Address")]
        public String Address { get { return order.Address.Street + ", " + order.Address.City + ", " + order.Address.ZIP + " " + order.Address.State; } }

        [Display(Name = "Order Items")]
        public ICollection<OrderItem> OrderItems { get { return order.OrderItems; } }

        [Display(Name = "Created On")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime CreatedOn { get { return order.CreatedOn.ToLocalTime(); } }

        [Display(Name = "Last Modified On")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime LastModified { get { return order.LastModified.ToLocalTime(); } }
    }
}

Medicus/Areas/Admin/Controllers/OrdersController.cs
using System.Diagnostics;
using System.Collections.Generic;
using System.Web.Mvc;
using Medicus.Models;
using Medicus.ViewModels;
using System.Linq;
using System.Net;

namespace Medicus.Areas.Admin.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Orders
        public ActionResult Index()
        {
            Order order = new Order();
            order.UpdateOrders();
            return View(new OrderViewModel(null));
        }

        [HttpPost]
        public JsonResult List()
        {
            List<OrderListViewModel> orderVMList = new List<OrderListViewModel>();

            foreach (var order in db.Orders)
            {
                orderVMList.Add(new OrderListViewModel(order));
            }
            return Json(orderVMList.OrderByDescending(ord => ord.CreatedOn));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            OrderViewModel viewModel = new OrderViewModel(order);
            ICollection<OrderItem> items = viewModel.OrderItems;
            foreach (OrderItem item in items)
            {
                item.Medicine = db.Medicines.Single(m => m.Id == item.Medicine.Id);
            }
            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(new OrderViewModel(order));
        }
    }
}

Medicus/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medicus.Models;
using Medicus.ViewModels;
using Microsoft.AspNet.Identity;
using System.Diagnostics;

namespace Medicus.Controllers
{
    public class OrderController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Order
        public ActionResult Index(string searchString)
        {
            var userId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == userId);
            Order ord = new Order();
            ord.UpdateOrders();
            //Check if current user has completed orders
            if (db.Orders.Any(o => o.Customer.Id == userId)) 
            {
                //ICollection<Order> orders = currentUser.Orders;
                List<OrderViewModel> orders = new List<OrderViewModel>();
                var userOrders = currentUser.Orders;
                foreach (Order order in userOrders)
                {
                    orders.Add(new OrderViewModel(order));
                }

                if (!String.IsNullOrEmpty(searchString))
                {
                    int searchId;
                    if (int.TryParse(searchString, out searchId))
                    {
                        searchId = Int32.Parse(searchString);

                        if (db.Orders.Any(o => o.Id == searchId))
                        {
                            return RedirectToAction("Details", new { OrderId = searchId });
                        }
                    }
                    else
                    {
                        return View(orders.OrderByDescending(o => o.CreatedOn));
                    }
                }
                return View(orders.OrderByDescending(o => o.CreatedOn));
            }
            else
            {
                return RedirectToAction("NoOrders");
            }
            
        }

        public ActionResult Details(int OrderId)
        {
            var userId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == userId);
            if (db.Orders.Any(o => o.Customer.Id == userId))
            {
                ICollection<Order> orders = currentUser.Orders;
                if (db.Orders.Any(o => o.Id == OrderId))
                {
                    Order order = currentUser.Orders.Single(o => o.Id == OrderId);
                    OrderViewModel viewModel = new OrderViewModel(order);
                    ICollection<OrderItem> items = viewModel.OrderItems;
                    foreach (OrderItem item in items)
                    {
                        item.Medicine = db.Medicines.Single(m => m.Id == item.Medicine.Id);
                    }
                    return View(viewModel);
                }
                else
                {
                    return View("Index", orders.OrderByDescending(o => o.CreatedOn));
                }
            }
            else
            {
                return RedirectToAction("NoOrders");
            }
        }

        public ActionResult NoOrders()
        {
            return View();
        }
    }
}

Medicus/Views/Order/Details.cshtml
@model Medicus.Models.OrderViewModel
@{
    ViewBag.Title = "Order Details";
}

@Styles.Render("~/Styles/shopping-order-status.css");

<div>
    <h2 class="pull-left">Order #@Model.Id </h2>
    <a href="@Url.Action("Index", "Order")" class="btn btn-primary pull-right">
        <span class="glyphicon glyphicon-backward"></span>&ensp;Back to your Orders
    </a>
</div>
<div class="row shop-tracking-status">
    <div class="col-md-12">
        <div class="well">
            <h4>Order items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Manufacturer</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (OrderItem item in Model.OrderItems)
            {
                        <tr>
                            <td>@item.Medicine.Name</td>
                            <td>@item.Medicine.Manufacturer</td>
                            <td>@item.Quantity</td>
                            <td>€ @item.Medicine.Price</td>
                            <td>€ @item.SubTotal</td>
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th>Total: </th>
                        <td>@Model.TotalPrice</td>
                    </tr>
                </tbody>
            </table>

            <hr />

            <h4>Your order status:</h4>
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="prefix">Date created:</span>
                    <span>@Model.CreatedOn</span>
                </li>
                <li class="list-group-item">
                    <span class="prefix">Last update:</span>
                    <span>@Model.LastModified</span>
                </li>
                <li class="list-group-item">
                    <span class="prefix">Review:</span>
                    <span>Customer's review</span>
                </li>
            </ul>
            <div class="order-status">
                <div class="order-status-timeline">
                    <!-- class names: c0 c1 c2 c3 and c4 -->
                    <div id="progress-bar" class="order-status-timeline-completion"></div>
                </div>
                <div class="image-order-status image-order-status-new active img-circle">
                    <span class="status">Received</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-active active img-circle">
                    <span class="status">Submitted</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-intransit active img-circle">
                    <span class="status">Shipped</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-delivered active img-circle">
                    <span class="status">Delivered</span>
                    <div class="icon"></div>
                </div>
                <div class="image-order-status image-order-status-completed active img-circle">
                    <span class="status">Completed</span>
                    <div class="icon"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/plugins/jquery/js")

<script>
    var status = '@Model.Status';
    var classname = "c0";
    if (status == "Received")  classname = "c0";
    if (status == "Submitted") classname = "c1";
    if (status == "Shipped") classname = "c2";
    if (status == "Delivered") classname = "c3";
    if (status == "Completed") classname = "c4";
    $("#progress-bar").addClass(classname);
</script>

Medicus/Views/Order/Index.cshtml
@model IEnumerable<Medicus.Models.OrderViewModel>
@{
    ViewBag.Title = "Your Orders";
}

@Styles.Render("~/Styles/shopping-order-status.css");

<h2>Your Orders</h2>
<hr />
<div>

    @using (Html.BeginForm("Index", "Order", FormMethod.Get))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <label for="inputOrderTrackingID" class="col-sm-2 control-label">Search order</label>
                <div class="col-md-8 col-sm-10">
                    @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Your Order Id here" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" id="shopGetOrderStatusID" class="btn btn-primary">Get Details</button>
                </div>
            </div>
        </div>      
    }
    
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
                @*@Html.DisplayNameFor(model => model.Id)*@
            </th>
            <th>
                Address
                @*@Html.DisplayNameFor(model => model.Address)*@
            </th>
            <th>
                Status
                @*@Html.DisplayNameFor(model => model.Status)*@
            </th>
            <th>
                Created On
                @*@Html.DisplayNameFor(model => model.CreatedOn)*@
            </th>
            <th>
                Total Price
                @*@Html.DisplayNameFor(model => model.TotalPrice)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Address.St), @Html.DisplayFor(modelItem => item.Address.City)
                    @Html.DisplayFor(modelItem => item.Address.ZIP), @Html.DisplayFor(modelItem => item.Address.State)*@
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    <a href="@Url.Action("Details", "Order", new { OrderId = item.Id })" class="btn btn-primary">Details</a>
                </td>
            </tr>
        }
    </tbody>

    
</table>

<hr />

Medicus/Views/Order/NoOrders.cshtml
@{
    ViewBag.Title = "No Orders found";
}

<div class="row">
    <div class="text-center">
        <h1 class="text-muted">No Orders found</h1>
        <br />
    </div>
</div>