Medicus/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Diagnostics;

namespace Medicus.Models
{
    public class ShoppingCart
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        string ShoppingCartId { get; set; }
        
        public const string CartSessionKey = "CartId";

        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        public static ShoppingCart GetCart(string CartId)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = CartId;
            return cart;
        }

        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }


        public int AddToCart(Medicine item)
        {

            // Get the matching cart and item instances
            var cartItem = db.Carts.SingleOrDefault(c => c.CartId == ShoppingCartId
                && c.MedicineId == item.Id);
            if (cartItem == null)
            {
                cartItem = new Cart
                {
                    MedicineId = item.Id,
                    CartId = ShoppingCartId,
                    Count = 1
                };

                db.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, then add one to the quantity
                cartItem.Count++;
            }

            db.SaveChanges();
            return cartItem.Count;
        }

        public int AddOneToCart(int id)
        {
            var cartItem = db.Carts.SingleOrDefault(c => c.CartId == ShoppingCartId
                && c.Id == id);
            cartItem.Count++;
            db.SaveChanges();
            return cartItem.Count;
        }

        public int RemoveOneFromCart(int id)
        {
            var cartItem = db.Carts.Single(cart => cart.CartId == ShoppingCartId &&
               cart.Id == id);
            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    db.Carts.Remove(cartItem);
                }

                db.SaveChanges();
            }
            return itemCount;
        }

        public int RemoveFromCart(int id)
        {
            var cartItem = db.Carts.Single(cart => cart.CartId == ShoppingCartId &&
               cart.Id == id);
            int itemCount = cartItem.Count;
            db.Carts.Remove(cartItem);
            db.SaveChanges();
            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = db.Carts.Where(cart => cart.CartId == ShoppingCartId);
            foreach (var cartItem in cartItems)
            {
                db.Carts.Remove(cartItem);
            }
            db.SaveChanges();
        }

        public List<Cart> GetCartItems()
        {
            return db.Carts.Where(cart => cart.CartId == ShoppingCartId).ToList();
        }

        public List<Cart> GetCartItemsNoTracking()
        {
            return db.Carts.AsNoTracking().Where(cart => cart.CartId == ShoppingCartId).ToList();
        }

        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in db.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();

            // Return 0 if all entries are null
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            // Multiply item price by count of that item to get 
            // the current price for each of those items in the cart
            // sum all item price totals to get the cart total
            decimal? total = (from cartItems in db.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count * cartItems.Medicine.Price).Sum();
            return total ?? decimal.Zero;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();

            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderItem
                {
                    Medicine = item.Medicine,
                    SubTotal = item.Medicine.Price,
                    Quantity = item.Count
                };

                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Medicine.Price);

                db.OrderItems.Add(orderDetail);

            }

            // Set the order's total to the orderTotal count
            order.TotalPrice = orderTotal;

            db.SaveChanges();
            EmptyCart();

            return order.Id;
        }

        // using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (context.User.Identity.IsAuthenticated)
                {
                    context.Session[CartSessionKey] = context.User.Identity.GetUserName();
                }
                else
                {

                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();

                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }

            return context.Session[CartSessionKey].ToString();
        }

        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carts.Where(c => c.CartId == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            db.SaveChanges();
        }
    }
}

Medicus/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using Medicus.Models;

namespace Medicus.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
        public decimal SubTotal(Cart cartItem)
        {
            { return cartItem.Medicine.Price * cartItem.Count; }
        }
        public int CartItemCount { get; set; }
    }
}

Medicus/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using Medicus.Models;
using Medicus.ViewModels;
using System.Diagnostics;

namespace Medicus.Controllers
{
    [AllowAnonymous]
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext storeDB = new ApplicationDbContext();

        // GET: ShoppingCart/Index
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartItemCount = cart.GetCount()
            };

            return View(viewModel);
        }

        //GET: ShoppingCart/AddToCart/1234?qnt=1
        public ActionResult AddToCart(int id, int qnt)
        {
            if (qnt > 0 && qnt < 21)
            {
                for (int i = 0; i < qnt; i++)
                {
                    // Retrieve item from database
                    var addedItem = storeDB.Medicines.Single(medicine => medicine.Id == id);
                    // Add to shopping cart
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.AddToCart(addedItem);
                }
            }
            return RedirectToAction("Index");
        }

        //AJAX
        [HttpPost]
        public ActionResult AddOneToCart(int id)
        {
            decimal medPrice = storeDB.Carts.Single(item => item.Id == id).Medicine.Price;
            
            // Add to shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int itemCount = cart.AddOneToCart(id);
            
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                ItemSubTotal = itemCount * medPrice,
                DeleteId = id
            };

            return Json(results);
        }

        // AJAX
        // Decrease quantity one by one
        [HttpPost]
        public ActionResult RemoveOneFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get medicine price to compute total price
            decimal medPrice = storeDB.Carts.Single(item => item.Id == id).Medicine.Price;

            int itemCount = cart.RemoveOneFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                ItemSubTotal = itemCount * medPrice,
                DeleteId = id
            };

            return Json(results);
        }


        // AJAX
        // Remove item from cart (set quantity to 0)
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of item to be removed
            string medName = storeDB.Carts.Single(item => item.Id == id).Medicine.Name;
            int itemCount = cart.RemoveFromCart(id);

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(medName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                ItemSubTotal = 0,
                DeleteId = id
            };

            return Json(results);
        }


        // required for cart summary on the navbar
        [AjaxChildActionOnly]
        public ActionResult Summary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("_SummaryPartial");
        }
    }
}

Medicus/Views/ShoppingCart/Index.cshtml
@model Medicus.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

@Styles.Render("~/Styles/Elements/ShoppingCart.css")


@if (Model.CartItemCount > 0)
{
    <div class="container">
        <div class="row">
            
            <div class="col-sm-12 col-md-10 col-md-offset-1">
                <h3>Shopping Cart</h3>
                <div class="alert alert-info fade out collapse" id="update-message">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <span id="msg-text"></span>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th style="min-width: 250px">Product</th>
                            <th class="text-center" style="min-width: 110px">Remove / Add</th>
                            <th>Quantity</th>
                            <th class="text-center">Unit Price</th>
                            <th class="text-center">Total</th>
                            <th>Remove Item</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CartItems)
                        {
                            <tr id="row-@item.Id">
                                <td class="col-sm-6 col-md-4">
                                    <div class="media">
                                        <a class="thumbnail pull-left" href="#">
                                            <img src="@Url.Content("~/Content/Images/pills.jpg")"
                                                 class="img-responsive" style="width: 72px; height: 72px;">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading">
                                                @Html.ActionLink(item.Medicine.Name, "Details", "Medicines", new { id = item.Medicine.Id }, null)
                                            </h4>
                                            <h5 class="media-heading"> by @Html.ActionLink(item.Medicine.Manufacturer, "Index", "Medicines", new { searchString = item.Medicine.Manufacturer }, null)</h5>
                                            <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                                        </div>
                                    </div>
                                </td>
                                <td class="col-sm-3 col-md-2" style="text-align: center">
                                    <button type="button" data-id="@item.Id" class="btn btn-danger remove-link">
                                        <span class="glyphicon glyphicon-minus"></span>
                                    </button>
                                    <button type="button" data-id="@item.Id" class="btn btn-success add-link">
                                        <span class="glyphicon glyphicon-plus"></span>
                                    </button>

                                </td>
                                <td class="col-sm-1 col-md-1" style="text-align: center" id="item-count-@item.Id">
                                    @item.Count
                                </td>

                                <td class="col-sm-1 col-md-1 text-center"><strong>&euro; @item.Medicine.Price</strong></td>
                                <td class="col-sm-1 col-md-1 text-center"><strong id="sub-total-@item.Id">&euro; @Model.SubTotal(@item)</strong></td>
                                <td class="col-sm-1 col-md-1">
                                    <button type="button" data-id="@item.Id" class="btn btn-danger remove-item-link">
                                        <span class="glyphicon glyphicon-remove"></span> Remove
                                    </button>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td><h5>Subtotal</h5></td>
                            <td class="text-right"><h5><strong class="cart-total">&euro; @Model.CartTotal</strong></h5></td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td><h5>Estimated shipping</h5></td>
                            <td class="text-right"><h5><strong>&euro; 0.00</strong></h5></td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td><h3>Total</h3></td>
                            <td class="text-right"><h3><strong class="cart-total">&euro; @Model.CartTotal</strong></h3></td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>   </td>
                            <td>
                                <a href="@Url.Action("Index", "Medicines")" class="btn btn-default">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
                                </a>
                            </td>
                            <td>
                                <a href="@Url.Action("AddressAndPayment", "Checkout")" class="btn btn-success">Checkout <span class="glyphicon glyphicon-play"></span></a>

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="text-center">
            <h1 class="text-muted">No items in shopping cart</h1>
            <br />
        </div>
    </div>
}

@Scripts.Render("~/bundles/plugins/jquery/js")
@Scripts.Render("~/Scripts/ShoppingCart/ShoppingCart.js")

Medicus/Views/ShoppingCart/_SummaryPartial.cshtml
@{
    int count = (int)ViewData["CartCount"];
}

<a href="@Url.Action("Index", "ShoppingCart")">
    Shopping Cart
    @if (count > 0)
    {
        <span class="badge">@count</span>
    }
</a>