Medicus/Models/Medicine.cs
using System;
using System.Web;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using Medicus.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Medicus
{
    public class Medicine : BaseEntity
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Drug { get; set; }
        [Required]
        public Category Category { get; set; }
        public string ShortInfo { get; set; }
        public string Description { get; set; }
        public string Indication { get; set; }
        public string Manufacturer { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public int InStockQty { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }
    }

    public enum Category
    {
        [Display(Name = "Antibiotic")]
        AntiBiotic,
        [Display(Name = "Anti-inflammatory")]
        AntiInflammatory,
        [Display(Name = "Steroid")]
        Steroid,
        [Display(Name = "Anti-hypertensive")]
        AntiHypertensive,
        [Display(Name = "Pain reliever")]
        PainReliever,
        [Display(Name = "Cholesterol reducer")]
        CholesterolReducer,
        [Display(Name = "Anti-depressant")]
        AntiDepressant,
        [Display(Name = "Other")]
        Other

    }
}

Medicus/ViewModels/MedicineViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medicus.Models
{
    public class MedicineViewModel

    {
        private Medicine medicine;

        public MedicineViewModel(Medicine medicine)
        {
            this.medicine = medicine;
        }

        public int Id { get { return medicine.Id; } }
        public string Name { get { return medicine.Name; } }
        public string Drug { get { return medicine.Drug; } }
        public string Description { get { return medicine.Description; } }
        public string Indication { get { return medicine.Indication; } }
        public string Manufacturer { get { return medicine.Manufacturer; } }
        public string ShortInfo { get { return medicine.ShortInfo; } }
        [Display(Name = "In Stock Qty")]
        public int InStockQty { get { return medicine.InStockQty; } }

        [Display(Name = "Category")]
        public string CategoryString
        {

            get
            {
                return EnumHelper.GetAttributeOfType<DisplayAttribute>(medicine.Category).Name;
            }

        }

        [Display(Name = "Price")]
        public string PriceString
        {
            get { return String.Format("€ {0:N2}", medicine.Price ); }

        }

        [Display(Name = "Short Information")]
        public string ShortInfoString
        {
            get
            {
                string info = medicine.ShortInfo;
                if (info != null)
                {
                    int last_pos;

                    if (info.Length > 120)
                    {
                        last_pos = info.LastIndexOf(" ", 120);
                        info = (last_pos == -1) ? info.Substring(0, 120) : info.Substring(0, last_pos);
                        info = info + " ...";
                    }
                }
                return info;

            }
        }
    }
}

Medicus/Areas/Admin/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Medicus;
using Medicus.Models;
using System.Data.Entity.Infrastructure;

namespace Medicus.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class MedicinesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Medicines
        public ActionResult Index()
        {
            return View(new MedicineViewModel(null));
        }


        [HttpPost]
        public JsonResult List()
        {

            List<MedicineViewModel> medicineVMList = new List<MedicineViewModel>();
            foreach (var medicine in db.Medicines)
            {
                medicineVMList.Add(new MedicineViewModel(medicine));
            }
            return Json(medicineVMList.OrderBy(s => s.Name));
        }


        // GET: Admin/Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(new MedicineViewModel(medicine));
        }

        // GET: Admin/Medicines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Medicines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Drug,Category,ShortInfo,Description,Indication,Manufacturer,Price,InStockQty,CreateDate,ModifiedDate,RowID")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicine);
        }

        // GET: Admin/Medicines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }



        // POST: Admin/Medicines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Drug,Category,ShortInfo,Description,Indication,Manufacturer,Price,InStockQty,CreateDate,ModifiedDate,RowID")] Medicine medicine, int? id, byte[] RowID)
        {
            
            var originalRowId = (from r in db.Medicines
                                 where r.Id == id
                                 select r.RowID).SingleOrDefault();

            //if medicine to be edited isn't in db anymore
            if (originalRowId == null)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes. The record was deleted by another user.");
                return View(medicine);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(medicine).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                    + "was modified by another user after you got the original value. The "
                    + "edit operation was canceled and the current values in the database "
                    + "have been displayed. If you still want to edit this record, click "
                    + "the Save button again. Otherwise click the Back to List button.");

                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }

            // set original rowId to model and send back to view 
            medicine.RowID = originalRowId;
            return View(medicine);
        }

        // GET: Admin/Medicines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(new MedicineViewModel(medicine));
        }

        // POST: Admin/Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Medicus/Controllers/MedicinesController.cs
using Medicus.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Medicus.Controllers
{
    [AllowAnonymous]
    public class MedicinesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Medicines
        public ActionResult Index(int? page, string searchString, int? filterCategory)
        {
            var medicines = from m in db.Medicines
                            select m;

            medicines = medicines.OrderBy(s => s.Name);

            int pageSize = 12;
            int pageNumber = (page ?? 1);

            if (!String.IsNullOrEmpty(searchString))
            {
                // search over all fields
                medicines = medicines.Where(s => s.Name.Contains(searchString) ||
                                                 s.Category.ToString() == searchString ||
                                                 s.Drug.Contains(searchString) ||
                                                 s.Indication.Contains(searchString) ||
                                                 s.ShortInfo.Contains(searchString) ||
                                                 s.Manufacturer.Contains(searchString) ||
                                                 s.Description.Contains(searchString)
                                                );
            }

            if (filterCategory.HasValue)
            {
                medicines = medicines.Where(x => (int) x.Category == filterCategory);
            }

            return View(medicines.ToPagedList(pageNumber, pageSize));

        }


        // GET: Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }
    }
}

Medicus/Views/Medicines/Details.cshtml
@model Medicus.Medicine

@{
    ViewBag.Title = "Details";
}
<div class="row">
    <div class="col-md-12">
        <h2>Details</h2>
    </div>
</div><!-- end row -->
<div class="row">
   <!-- <div class="col-md-12">
        <h2>@ViewBag.Title </h2>
    </div>-->
    <div class="col-md-6 col-sm-5">
        <img src="@Url.Content("~/Content/Images/pills.jpg")"
             alt=@Html.DisplayFor(model => model.Name)
             class="img-responsive" />
    </div>
    <div class="col-md-6 col-sm-7">
        <div class="row">
            <div class="col-md-12">
                <h1>@Html.DisplayFor(model => model.Name)</h1>
            </div>
        </div><!-- end row-->
        <div class="row">
            <div class="col-md-12">
                <span class="label label-primary" style="font-size: 14px">Vintage</span>
                <span class="monospaced">No. 1960140180</span>
            </div>
        </div><!-- end row -->
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <p class="description text-justify">
                    @Html.DisplayFor(model => model.ShortInfo)
                </p>
            </div>
        </div><!-- end row -->
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <span class="sr-only">Four out of Five Stars</span>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                <span class="label label-info" style="font-size: 14px">61</span>
            </div>
            <div class="col-md-6 col-sm-6">
                <span class="label label-success pull-right" style="font-size: 18px">In Stock</span>
                @*<span class="monospaced">Write a Review</span>*@
            </div>
        </div><!-- end row -->
        <div class="row">
            <div class="col-md-12 bottom-rule">
                <h2 class="product-price">&euro; @Html.DisplayFor(model => model.Price)</h2> 
            </div>
        </div><!-- end row -->
        <hr />
        <div class="row">
            @*<p></p>
                <div class="row">
                    <div class="col-md-6">
                        <a href="@Url.Action("Details","Medicines", new { id = item.Id })" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-info-sign"></span> See more</a>
                    </div>
                    <div class="col-md-6">
                        <a href="#" class="btn btn-warning btn-block"><span class="glyphicon glyphicon-shopping-cart"></span> Add to cart</a>
                    </div>
                </div>
                <p></p>*@
            @*<div class="col-md-6">
                <div class="btn-group">
                    <span class="btn btn-default btn-md">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </span>
                    <input class="btn btn-default btn-md col-xs-4" value="1" />
                    <span class="btn btn-default btn-md">
                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                    </span>
                </div>
            </div>*@
            <div class="col-md-1 col-sm-0 col-xm-1"></div>
            <div class="center col-md-4 col-sm-5 col-xs-5">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="button" class="quantity-left-minus btn btn-danger btn-number" data-type="minus" data-field="">
                            <span class="glyphicon glyphicon-minus"></span>
                        </button>
                    </span>
                    <input type="number" id="quantity" name="quantity" class="form-control input-number" value="1" readonly>
                    <span class="input-group-btn">
                        <button type="button" class="quantity-right-plus btn btn-success btn-number" data-type="plus" data-field="">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2" style="padding-top: 5px; padding-left: 0">
                <span id="reset-count" class="btn btn-xs btn-default">Reset</span>
            </div>
            <div class="col-md-4 col-sm-5 col-xs-4 text-center">
                @*<a href="@Url.Action("AddToCart","ShoppingCart", new { id = Model.Id, qnt = 2 })" class="btn btn-warning btn-block">
                    <span class="glyphicon glyphicon-shopping-cart"></span> Add to cart
                </a>*@
                <a id="add-to-cart" data-id="@Html.DisplayFor(model => model.Id)" class="btn btn-warning btn-block">
                    <span class="glyphicon glyphicon-shopping-cart"></span> Add to cart
                </a>
            </div>
        </div>
        <hr />
        <div class="row">
            
            @*<div class="col-md-4 col-md-offset-1 text-center">
                <a class="monospaced" href="#">Add to Shopping List</a>
            </div>*@
        </div><!-- end row -->
        <div class="row">
            <div class="col-md-12">
                <p>To order by telephone, <a href="tel:18005551212">please call 1-800-555-1212</a></p>
            </div>
        </div><!-- end row -->
    </div>
</div><!-- end row -->

@Scripts.Render("~/bundles/plugins/jquery/js")
@Scripts.Render("~/Scripts/Medicines/PlusMinusInput.js")
@Scripts.Render("~/Scripts/ShoppingCart/ShoppingCart.js")


<div class="help-block"></div>
<div class="row">
    <div class="col-md-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#description"
                   aria-controls="description"
                   role="tab"
                   data-toggle="tab">Description</a>
            </li>
            <li role="presentation">
                <a href="#features"
                   aria-controls="features"
                   role="tab"
                   data-toggle="tab">Features</a>
            </li>
            <li role="presentation">
                <a href="#notes"
                   aria-controls="notes"
                   role="tab"
                   data-toggle="tab">Notes</a>
            </li>
            <li role="presentation">
                <a href="#reviews"
                   aria-controls="reviews"
                   role="tab"
                   data-toggle="tab">Reviews</a>
            </li>
        </ul>
        <div class="panel-body">
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="description">
                    <p class="top-10">
                        1 The 'Brownie' Flash B is a box camera taking 2&frac14; × 3&frac14;" frames on 620 film, made of sheet metal by Kodak Ltd. in England, 1958-60.
                        A more luxurious version of the Brownie Six-20 Model F, it has a two-speed shutter (1/80, 1/40 +B), a close-focus (5-10ft) lens, a yellow filter and flash sync. The Flash B is very similar to the Brownie Flash IV, adding a two-speed shutter but lacking a tripod bush.
                    </p>
                    <p>
                        <small>
                            (source <a href="http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B">http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B</a>)
                        </small>
                    </p>
                </div>
                <div role="tabpanel" class="tab-pane top-10" id="features">
                    <p class="top-10">
                        2 The 'Brownie' Flash B is a box camera taking 2&frac14; × 3&frac14;" frames on 620 film, made of sheet metal by Kodak Ltd. in England, 1958-60.
                        A more luxurious version of the Brownie Six-20 Model F, it has a two-speed shutter (1/80, 1/40 +B), a close-focus (5-10ft) lens, a yellow filter and flash sync. The Flash B is very similar to the Brownie Flash IV, adding a two-speed shutter but lacking a tripod bush.
                    </p>
                    <p>
                        <small>
                            (source <a href="http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B">http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B</a>)
                        </small>
                    </p>
                </div>
                <div role="tabpanel" class="tab-pane" id="notes">
                    <p class="top-10">
                        3 The 'Brownie' Flash B is a box camera taking 2&frac14; × 3&frac14;" frames on 620 film, made of sheet metal by Kodak Ltd. in England, 1958-60.
                        A more luxurious version of the Brownie Six-20 Model F, it has a two-speed shutter (1/80, 1/40 +B), a close-focus (5-10ft) lens, a yellow filter and flash sync. The Flash B is very similar to the Brownie Flash IV, adding a two-speed shutter but lacking a tripod bush.
                    </p>
                    <p>
                        <small>
                            (source <a href="http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B">http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B</a>)
                        </small>
                    </p>
                </div>
                <div role="tabpanel" class="tab-pane" id="reviews">
                    <p class="top-10">
                        4 The 'Brownie' Flash B is a box camera taking 2&frac14; × 3&frac14;" frames on 620 film, made of sheet metal by Kodak Ltd. in England, 1958-60.
                        A more luxurious version of the Brownie Six-20 Model F, it has a two-speed shutter (1/80, 1/40 +B), a close-focus (5-10ft) lens, a yellow filter and flash sync. The Flash B is very similar to the Brownie Flash IV, adding a two-speed shutter but lacking a tripod bush.
                    </p>
                    <p>
                        <small>
                            (source <a href="http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B">http://camerapedia.wikia.com/wiki/Kodak_Brownie_Flash_B</a>)
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div><!-- end row -->

Medicus/Views/Medicines/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Medicus.Medicine>


@{
    ViewBag.Title = "Medicines";
}

<!-- this is the search/filter bar-->
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        @using (Html.BeginForm("Index", "Medicines", FormMethod.Get))
            {
            <div class="input-group input-group-lg">
                <div class="input-group-btn search-panel">
                    @BootstrapHtml.DropdownButton("filter-button", new Category(), "Filter by")
                </div>
                <input type="hidden" name="filtercategory" value="all" id="filter-category">
                @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Search" })
                <span class="input-group-btn">
                    <a href="@Url.Action("Index", "Medicines")" class="btn btn-info"><span class="glyphicon glyphicon-repeat"></span></a>
                    <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </span>
            </div>
        }
    </div>
</div>

@if (Model.PageCount > 0)
{
    <div class="row">
        <!-- adding some vertical space -->
        <div class="form-group">
            &nbsp;
        </div>
        <div class="col-md-12">
            @foreach (var item in Model)
            {
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <h4 class="text-center"><span class="label label-info">@Html.DisplayFor(modelItem => item.Drug)</span></h4>
                    <a href="@Url.Action("Details", "Medicines", new { Id = item.Id })"><img src="@Url.Content("~/Content/Images/pills.jpg")" class="img-responsive"></a>
                    <div class="caption">
                        <div class="row">
                            <div class="col-md-6 col-xs-6">
                                <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                                <p>
                                    <small>
                                        @Html.DisplayFor(modelItem => item.Manufacturer)
                                    </small>
                                </p>
                            </div>
                            <div class="col-md-6 col-xs-6 price">
                                <h3 class="text-center">
                                    <label>&euro; @Html.DisplayFor(modelItem => item.Price)</label>
                                </h3>
                            </div>
                        </div>
                        <p></p>
                        <div class="row">
                            <div class="col-md-6">
                                <a href="@Url.Action("Details", "Medicines", new { Id = item.Id })" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-info-sign"></span> See more</a>
                            </div>
                            <div class="col-md-6">
                                <a href="@Url.Action("AddToCart","ShoppingCart", new { id = item.Id, qnt = 1 })" class="btn btn-warning btn-block"><span class="glyphicon glyphicon-shopping-cart"></span> Add to cart</a>
                            </div>
                        </div>
                        <p></p>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="text-center">
            <h1 class="text-muted">No Medicines found</h1>
            <br />
        </div>
    </div>
}
@if (Model.PageCount > 1)
{
    <div class="row">
        <div class="col-md-12 text-center">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
}
@section scripts
{
    <script src="@Url.Content("~/Scripts/Medicines/index.js")"></script>
}